### ISSUE TITLE
UNetExtractor

### ISSUE THREAD

**Issue by sunnyYaSky** [MrZilinXiao/Hyper-Table-OCR#1]
能分享一下unetExtractor 模块吗  
谢谢~

**Comment by MrZilinXiao** [comment]
Sorry, I didn't realize that `extractor.py` was in the ignored list of Git. Already fixed in https://github.com/MrZilinXiao/Hyper-Table-OCR/commit/1432b1f7626cc96f868b329b7c6d1e58e49f813e.

Sorry again for the inconvenience.

**Comment by MrZilinXiao** [comment]
Close this issue due to no further reply. Reopen it if necessary.
