### ISSUE TITLE
table line

### ISSUE THREAD

**Issue by Hamdi-Ben-Abdallah** [MrZilinXiao/Hyper-Table-OCR#13]
Hello,

Thank you for this beautiful work.

I have two questions to ask you:

I did not understand the role of Unet in this project. Did you use it to extract the lines from the table? Why did you use it?

If yes, did you use this code https://github.com/chineseocr/table-detect ?

Thanks in advance.

**Comment by MrZilinXiao** [comment]
Yes, and sorry for not including it in the acknowledgement. (I must forget it...) I'll add it right away.

The reason is that we need pixel-level prediction on table lines to correctly rebuild the structure of the table.
