### ISSUE TITLE
你好，请问表格结构是采用哪个数据集？

### ISSUE THREAD

**Issue by 965662766** [MrZilinXiao/Hyper-Table-OCR#5]

**Comment by MrZilinXiao** [comment]
Duplicated with https://github.com/MrZilinXiao/Hyper-Table-OCR/issues/3.

**Comment by 965662766** [comment]
好的，非常感谢！

**Comment by 965662766** [comment]
![image](https://user-images.githubusercontent.com/85744622/129877378-ad31cdde-8b36-4eca-8f08-57fa9bd890b0.png)
你好，我看了下，表格结构标线的数据集就是这些吗

**Comment by MrZilinXiao** [comment]
在本项目中我们只使用了上述项目的预训练权重，这也是为何我们仍依赖tensorflow的原因。
