### ISSUE TITLE
报错cannot open resource

### ISSUE THREAD

**Issue by LeonPython** [MrZilinXiao/Hyper-Table-OCR#9]
你好，在识别表格的时候报错cannot open resource ，请问你知道是什么原因吗？
![image](https://user-images.githubusercontent.com/23022920/139708647-d34b3540-6db9-4ea0-adef-e52e9c2c1b4d.png)

**Comment by MrZilinXiao** [comment]
请您尝试注释掉`app.py`的try-except语句并在控制台查看完整的报错信息，或者使用调试器查看Exception的具体内容☺️
